# -*- coding: utf-8 -*-
"""exp1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10WgTLfATplevuvmJvApodFi1ymXick2J
"""

a=11
b=20
c=a+b
print(c)

a=11
b=22
c=a+b
print(c)